[package]
name = "platformer_demo"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "platformer_demo"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
forge2d = { path = "../../forge2d" }

